// bindings.test.ts — contract tests for the generated bindings
// (src/lib/contracts/addresses.ts + tokens.ts), per contracts/frontend-module-api.md §3
// and 002 tasks.md T009. Must pass BOTH before regeneration (single-chain DEPLOYMENTS,
// no faucet field) and after multi-chain sync-deploy (31337 + 11155111 keys, faucet
// field present, missing chain ZERO-filled).

import { describe, it, expect } from "vitest";
import { ANVIL_CHAIN_ID } from "@/lib/chains";
import {
  DEPLOYMENTS,
  getDeployment,
  isDeploymentConfigured,
  type Deployment,
} from "@/lib/contracts/addresses";
import {
  TOKENS,
  TOKEN_LIST,
  getTokenAddress,
  isValidAddress,
} from "@/lib/contracts/tokens";

const ZERO_ADDR = "0x0000000000000000000000000000000000000000";
const REAL_ADDR = "0x1111111111111111111111111111111111111111";
// Sepolia chain id — chains.ts does not export it yet (T004); keep the literal
// here so the suite compiles before and after regeneration.
const SEPOLIA_CHAIN_ID = 11155111;
// Committed Sepolia deployment (T013/T014) — stable, never regenerated by local
// anvil syncs (sync-deploy only rewrites 31337 from anvil broadcasts).
const SEPOLIA_FACTORY = "0xc32bc046beafd48827f3d55356568476df322dde";
const SEPOLIA_WETH = "0xd1647800688ccb78c1f378329110fd10791b8af9";

const TOKEN_SYMBOLS = ["WETH", "USDC", "DAI", "WBTC"] as const;

/**
 * Build a Deployment-shaped fixture. Core addresses are REAL unless zeroCore is
 * set; the faucet property is only present when requested so the same fixture
 * compiles against both the pre-regeneration interface (no faucet) and the
 * post-regeneration one (faucet required).
 */
function makeFixture(opts: { zeroCore?: boolean; zeroFaucet?: boolean } = {}): Deployment {
  const core: string = opts.zeroCore ? ZERO_ADDR : REAL_ADDR;
  const tokens: Record<(typeof TOKEN_SYMBOLS)[number], string> = {
    WETH: REAL_ADDR,
    USDC: REAL_ADDR,
    DAI: REAL_ADDR,
    WBTC: REAL_ADDR,
  };
  return {
    factory: core,
    router: core,
    weth: core,
    ...(opts.zeroFaucet ? { faucet: ZERO_ADDR } : {}),
    tokens,
  } as Deployment;
}

describe("bindings (addresses.ts)", () => {
  describe("getDeployment", () => {
    it("returns null for a null chainId", () => {
      expect(getDeployment(null)).toBeNull();
    });

    it("returns null for an unknown chain without throwing", () => {
      expect(() => getDeployment(999999)).not.toThrow();
      expect(getDeployment(999999)).toBeNull();
    });

    it("returns a well-formed deployment for the anvil chain (31337)", () => {
      const d = getDeployment(ANVIL_CHAIN_ID);
      expect(d).not.toBeNull();
      if (d) {
        expect(d.factory).toMatch(/^0x[0-9a-fA-F]{40}$/);
        expect(d.router).toMatch(/^0x[0-9a-fA-F]{40}$/);
        expect(d.weth).toMatch(/^0x[0-9a-fA-F]{40}$/);
        for (const symbol of TOKEN_SYMBOLS) {
          expect(d.tokens[symbol]).toMatch(/^0x[0-9a-fA-F]{40}$/);
        }
      }
    });

    it("keeps the anvil deployment configured", () => {
      // Non-ZERO core addresses on 31337 in both the current and regenerated state.
      expect(isDeploymentConfigured(getDeployment(ANVIL_CHAIN_ID))).toBe(true);
    });

    it("reports the Sepolia deployment as configured with the committed addresses", () => {
      expect(() => getDeployment(SEPOLIA_CHAIN_ID)).not.toThrow();
      const d = getDeployment(SEPOLIA_CHAIN_ID);
      expect(d).not.toBeNull();
      if (d) {
        expect(d.factory).toBe(SEPOLIA_FACTORY);
        expect(d.weth).toBe(SEPOLIA_WETH);
        expect(isDeploymentConfigured(d)).toBe(true);
      }
    });

    it("exposes faucet as a string on the anvil deployment when present", () => {
      const d = getDeployment(ANVIL_CHAIN_ID);
      if (d && "faucet" in d) {
        expect(typeof d.faucet).toBe("string");
        // A ZERO faucet must not disable an otherwise-configured deployment.
        if (d.faucet === ZERO_ADDR) {
          expect(isDeploymentConfigured(d)).toBe(true);
        }
      }
    });
  });

  describe("isDeploymentConfigured", () => {
    it("returns false for null/undefined", () => {
      expect(isDeploymentConfigured(null)).toBe(false);
      expect(isDeploymentConfigured(undefined)).toBe(false);
    });

    it("returns false for a ZERO-filled deployment", () => {
      expect(isDeploymentConfigured(makeFixture({ zeroCore: true }))).toBe(false);
    });

    it("returns false when only one core address is ZERO", () => {
      const d = makeFixture();
      d.factory = ZERO_ADDR;
      expect(isDeploymentConfigured(d)).toBe(false);
    });

    it("returns true when core addresses are non-ZERO and faucet is ZERO", () => {
      expect(isDeploymentConfigured(makeFixture({ zeroFaucet: true }))).toBe(true);
    });

    it("returns true when core addresses are non-ZERO and faucet is missing", () => {
      expect(isDeploymentConfigured(makeFixture())).toBe(true);
    });
  });

  describe("DEPLOYMENTS shape", () => {
    it("is keyed by chain id with Deployment values", () => {
      for (const chainId of Object.keys(DEPLOYMENTS).map(Number)) {
        const d = DEPLOYMENTS[chainId];
        expect(typeof d.factory).toBe("string");
        expect(typeof d.router).toBe("string");
        expect(typeof d.weth).toBe("string");
        expect(typeof d.tokens.WETH).toBe("string");
        expect(typeof d.tokens.USDC).toBe("string");
        expect(typeof d.tokens.DAI).toBe("string");
        expect(typeof d.tokens.WBTC).toBe("string");
      }
    });
  });
});

describe("bindings (tokens.ts)", () => {
  it("exposes the four known tokens", () => {
    expect(Object.keys(TOKENS)).toEqual(["WETH", "USDC", "DAI", "WBTC"]);
    expect(TOKEN_LIST).toHaveLength(4);
  });

  it("keeps static metadata plus an addressByChain map per token", () => {
    for (const symbol of TOKEN_SYMBOLS) {
      const token = TOKENS[symbol];
      expect(token.symbol).toBe(symbol);
      expect(typeof token.name).toBe("string");
      expect(typeof token.decimals).toBe("number");
      expect(token.addressByChain).toBeTypeOf("object");
      // Both states must carry the anvil key; Sepolia is added by multi-chain sync-deploy.
      expect(ANVIL_CHAIN_ID in token.addressByChain).toBe(true);
    }
  });

  it("keeps addressByChain consistent with DEPLOYMENTS", () => {
    for (const chainId of Object.keys(DEPLOYMENTS).map(Number)) {
      const dep = DEPLOYMENTS[chainId];
      for (const symbol of TOKEN_SYMBOLS) {
        expect(chainId in TOKENS[symbol].addressByChain).toBe(true);
        const depAddr = dep.tokens[symbol];
        const tokAddr = TOKENS[symbol].addressByChain[chainId];
        if (depAddr === ZERO_ADDR) {
          expect(tokAddr).toBeNull();
        } else {
          expect(tokAddr).toBe(depAddr);
        }
      }
    }
  });

  it("getTokenAddress resolves per chain and falls back to null", () => {
    expect(getTokenAddress("WETH", ANVIL_CHAIN_ID)).not.toBeNull();
    // Sepolia is configured since T013/T014 — resolves to the committed address.
    expect(getTokenAddress("WETH", SEPOLIA_CHAIN_ID)).toBe(SEPOLIA_WETH);
    expect(getTokenAddress("WETH", 999999)).toBeNull();
  });

  it("isValidAddress rejects the PLACEHOLDER and accepts real addresses", () => {
    expect(isValidAddress(ZERO_ADDR)).toBe(false);
    expect(isValidAddress(REAL_ADDR)).toBe(true);
    expect(isValidAddress(null)).toBe(false);
    expect(isValidAddress(undefined)).toBe(false);
  });
});
