// sync-deploy.ts — read `contracts/broadcast/<chainId>/run-latest.json` + ABI
// artifacts from `contracts/out/` and regenerate addresses.ts + abis.ts.
// Spec: contracts/frontend-module-api.md §9, research.md R0.9.

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface BroadcastTx {
  contractName?: string;
  contractAddress?: string;
  function?: string;
  transactionType?: string;
}

interface BroadcastFile {
  chain?: number;
  transactions?: BroadcastTx[];
}

interface Deployment {
  factory: string;
  router: string;
  weth: string;
  tokens: { WETH: string; USDC: string; DAI: string; WBTC: string };
}

const ZERO = "0x0000000000000000000000000000000000000000";
const PLACEHOLDER = "0x0000000000000000000000000000000000000000";

function repoRoot(): string {
  // frontend/scripts/sync-deploy.ts -> frontend/ -> repo root
  return resolve(__dirname, "..", "..");
}

function readBroadcast(chainId: number): BroadcastFile | null {
  const path = join(repoRoot(), "contracts", "broadcast", String(chainId), "run-latest.json");
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8")) as BroadcastFile;
}

function findContractAddress(broadcast: BroadcastFile, contractName: string): string {
  for (const tx of broadcast.transactions ?? []) {
    if (tx.contractName === contractName && tx.contractAddress) {
      return tx.contractAddress;
    }
  }
  return ZERO;
}

function buildDeployment(chainId: number): Deployment {
  const broadcast = readBroadcast(chainId);
  if (!broadcast) {
    return {
      factory: ZERO,
      router: ZERO,
      weth: ZERO,
      tokens: { WETH: ZERO, USDC: ZERO, DAI: ZERO, WBTC: ZERO },
    };
  }
  return {
    factory: findContractAddress(broadcast, "UniswapV2Factory"),
    router: findContractAddress(broadcast, "UniswapV2Router02"),
    weth: findContractAddress(broadcast, "WETH9"),
    tokens: {
      WETH: findContractAddress(broadcast, "WETH9"),
      USDC: findContractAddress(broadcast, "MockERC20"),
      // Heuristic: later MockERC20 deployments are DAI / WBTC. A future
      // enhancement is to use the constructor args from the broadcast file.
      DAI: ZERO,
      WBTC: ZERO,
    },
  };
}

function readAbi(contractName: string): unknown[] | null {
  const path = join(repoRoot(), "contracts", "out", `${contractName}.sol`, `${contractName}.json`);
  if (!existsSync(path)) return null;
  const json = JSON.parse(readFileSync(path, "utf8")) as { abi?: unknown[] };
  return json.abi ?? null;
}

function listOutContracts(): string[] {
  const outDir = join(repoRoot(), "contracts", "out");
  if (!existsSync(outDir)) return [];
  return readdirSync(outDir)
    .filter((d) => d.endsWith(".sol"))
    .map((d) => d.replace(/\.sol$/, ""));
}

function writeAddresses(deployments: Record<number, Deployment>): void {
  const path = join(repoRoot(), "frontend", "src", "lib", "contracts", "addresses.ts");
  const content = `// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.
import { ANVIL_CHAIN_ID, SEPOLIA_CHAIN_ID } from "../chains";

const ZERO = "0x0000000000000000000000000000000000000000" as const;

export interface Deployment {
  factory: \`0x\${string}\`;
  router: \`0x\${string}\`;
  weth: \`0x\${string}\`;
  tokens: {
    WETH: \`0x\${string}\`;
    USDC: \`0x\${string}\`;
    DAI: \`0x\${string}\`;
    WBTC: \`0x\${string}\`;
  };
}

export const DEPLOYMENTS: Record<number, Deployment> = {
  [ANVIL_CHAIN_ID]: ${JSON.stringify(deployments[31337] ?? null)},
  [SEPOLIA_CHAIN_ID]: ${JSON.stringify(deployments[11155111] ?? null)},
};

export function getDeployment(chainId: number | null): Deployment | null {
  if (chainId === null) return null;
  return DEPLOYMENTS[chainId] ?? null;
}

export function isDeploymentConfigured(d: Deployment | null | undefined): d is Deployment {
  if (!d) return false;
  return d.factory !== ZERO && d.router !== ZERO && d.weth !== ZERO;
}
`;
  writeFileSync(path, content, "utf8");
}

function writeTokens(deployments: Record<number, Deployment>): void {
  const path = join(repoRoot(), "frontend", "src", "lib", "contracts", "tokens.ts");
  const anvil = deployments[31337] ?? null;
  const sepolia = deployments[11155111] ?? null;
  const content = `// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.

const PLACEHOLDER = "0x0000000000000000000000000000000000000000" as const;
function emptyAddresses(): Record<number, \`0x\${string}\` | null> {
  return {
    31337: ${anvil ? `("${anvil.tokens.WETH || PLACEHOLDER}" as \`0x\${string}\`)` : "null"},
    11155111: ${sepolia ? `("${sepolia.tokens.WETH || PLACEHOLDER}" as \`0x\${string}\`)` : "null"},
  };
}

// Static metadata; addresses filled in by sync-deploy.
export const TOKENS = {
  WETH: { symbol: "WETH" as const, name: "Wrapped Ether", decimals: 18, addressByChain: emptyAddresses() },
  USDC: { symbol: "USDC" as const, name: "USD Coin", decimals: 6, addressByChain: { 31337: ${anvil ? `("${anvil.tokens.USDC || PLACEHOLDER}" as \`0x\${string}\`)` : "null"}, 11155111: ${sepolia ? `("${sepolia.tokens.USDC || PLACEHOLDER}" as \`0x\${string}\`)` : "null"} } },
  DAI:  { symbol: "DAI" as const,  name: "Dai Stablecoin", decimals: 18, addressByChain: { 31337: ${anvil ? `("${anvil.tokens.DAI || PLACEHOLDER}" as \`0x\${string}\`)` : "null"}, 11155111: ${sepolia ? `("${sepolia.tokens.DAI || PLACEHOLDER}" as \`0x\${string}\`)` : "null"} } },
  WBTC: { symbol: "WBTC" as const, name: "Wrapped BTC",  decimals: 8,  addressByChain: { 31337: ${anvil ? `("${anvil.tokens.WBTC || PLACEHOLDER}" as \`0x\${string}\`)` : "null"}, 11155111: ${sepolia ? `("${sepolia.tokens.WBTC || PLACEHOLDER}" as \`0x\${string}\`)` : "null"} } },
};

export const TOKEN_LIST = Object.values(TOKENS);
export const KNOWN_PAIRS = [
  ["WETH", "USDC"],
  ["WETH", "DAI"],
  ["WETH", "WBTC"],
  ["USDC", "DAI"],
  ["USDC", "WBTC"],
  ["DAI", "WBTC"],
] as const;

export function getToken(symbol: "WETH" | "USDC" | "DAI" | "WBTC") { return TOKENS[symbol]; }
export function getTokenAddress(symbol: "WETH" | "USDC" | "DAI" | "WBTC", chainId: number) { return TOKENS[symbol].addressByChain[chainId] ?? null; }
export function isValidAddress(addr: string | null | undefined): addr is \`0x\${string}\` {
  return typeof addr === "string" && addr.length === 42 && addr.startsWith("0x") && addr !== PLACEHOLDER;
}
`;
  writeFileSync(path, content, "utf8");
}

function writeAbis(): void {
  const contracts = listOutContracts();
  const entries: string[] = [];
  for (const name of contracts) {
    const abi = readAbi(name);
    if (!abi) continue;
    // Serialize as JSON for embedding in a TS file.
    entries.push(`export const ${name}_ABI = ${JSON.stringify(abi, null, 2)} as const;`);
  }
  const content = `// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.\n\n${entries.join("\n\n")}\n`;
  const path = join(repoRoot(), "frontend", "src", "lib", "contracts", "abis.generated.ts");
  writeFileSync(path, content, "utf8");
}

function main(): void {
  const chainIds = [31337, 11155111];
  const deployments: Record<number, Deployment> = {};
  for (const id of chainIds) {
    deployments[id] = buildDeployment(id);
  }
  writeAddresses(deployments);
  writeTokens(deployments);
  writeAbis();

  const contracts = listOutContracts();
  if (contracts.length > 0) {
    console.log(`Wrote addresses.ts, tokens.ts, and abis.generated.ts (${contracts.length} contracts).`);
  } else {
    console.log("Wrote addresses.ts and tokens.ts. No compiled ABIs in contracts/out — run `forge build` to populate.");
  }
}

main();
