// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.
import { ANVIL_CHAIN_ID, SEPOLIA_CHAIN_ID } from "../chains";

const ZERO = "0x0000000000000000000000000000000000000000" as const;

export interface Deployment {
  factory: `0x${string}`;
  router: `0x${string}`;
  weth: `0x${string}`;
  tokens: {
    WETH: `0x${string}`;
    USDC: `0x${string}`;
    DAI: `0x${string}`;
    WBTC: `0x${string}`;
  };
}

export const DEPLOYMENTS: Record<number, Deployment> = {
  [ANVIL_CHAIN_ID]: {"factory":"0x8a791620dd6260079bf849dc5567adc3f2fdc318","router":"0x0000000000000000000000000000000000000000","weth":"0x610178da211fef7d417bc0e6fed39f05609ad788","tokens":{"WETH":"0x610178da211fef7d417bc0e6fed39f05609ad788","USDC":"0xb7f8bc63bbcad18155201308c8f3540b07f84f5e","DAI":"0x0000000000000000000000000000000000000000","WBTC":"0x0000000000000000000000000000000000000000"}},
  [SEPOLIA_CHAIN_ID]: {"factory":"0x0000000000000000000000000000000000000000","router":"0x0000000000000000000000000000000000000000","weth":"0x0000000000000000000000000000000000000000","tokens":{"WETH":"0x0000000000000000000000000000000000000000","USDC":"0x0000000000000000000000000000000000000000","DAI":"0x0000000000000000000000000000000000000000","WBTC":"0x0000000000000000000000000000000000000000"}},
};

export function getDeployment(chainId: number | null): Deployment | null {
  if (chainId === null) return null;
  return DEPLOYMENTS[chainId] ?? null;
}

export function isDeploymentConfigured(d: Deployment | null | undefined): d is Deployment {
  if (!d) return false;
  return d.factory !== ZERO && d.router !== ZERO && d.weth !== ZERO;
}
