// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.

const PLACEHOLDER = "0x0000000000000000000000000000000000000000" as const;
function makeAddresses(a31337: `0x${string}` | null, a11155111: `0x${string}` | null): Record<number, `0x${string}` | null> {
  return { 31337: a31337, 11155111: a11155111 };
}

// Static metadata; addresses filled in by sync-deploy.
export const TOKENS = {
  WETH: { symbol: "WETH" as const, name: "Wrapped Ether", decimals: 18, addressByChain: makeAddresses("0xc5a5c42992decbae36851359345fe25997f5c42d" as `0x${string}`, null) },
  USDC: { symbol: "USDC" as const, name: "USD Coin", decimals: 6, addressByChain: makeAddresses("0x4a679253410272dd5232b3ff7cf5dbb88f295319" as `0x${string}`, null) },
  DAI:  { symbol: "DAI" as const,  name: "Dai Stablecoin", decimals: 18, addressByChain: makeAddresses("0x7a2088a1bfc9d81c55368ae168c2c02570cb814f" as `0x${string}`, null) },
  WBTC: { symbol: "WBTC" as const, name: "Wrapped BTC",  decimals: 8,  addressByChain: makeAddresses("0x09635f643e140090a9a8dcd712ed6285858cebef" as `0x${string}`, null) },
};

export const TOKEN_LIST = Object.values(TOKENS);
export const KNOWN_PAIRS = [
  ["WETH", "USDC"],
  ["WETH", "DAI"],
  ["WETH", "WBTC"],
  ["USDC", "DAI"],
  ["USDC", "WBTC"],
  ["DAI", "WBTC"],
] as const;

export function getToken(symbol: "WETH" | "USDC" | "DAI" | "WBTC") { return TOKENS[symbol]; }
export function getTokenAddress(symbol: "WETH" | "USDC" | "DAI" | "WBTC", chainId: number) { return TOKENS[symbol].addressByChain[chainId] ?? null; }
export function isValidAddress(addr: string | null | undefined): addr is `0x${string}` {
  return typeof addr === "string" && addr.length === 42 && addr.startsWith("0x") && addr !== PLACEHOLDER;
}
