// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.

const PLACEHOLDER = "0x0000000000000000000000000000000000000000" as const;
function makeAddresses(a31337: `0x${string}` | null, a11155111: `0x${string}` | null): Record<number, `0x${string}` | null> {
  return { 31337: a31337, 11155111: a11155111 };
}

// Static metadata; addresses filled in by sync-deploy.
export const TOKENS = {
  WETH: { symbol: "WETH" as const, name: "Wrapped Ether", decimals: 18, addressByChain: makeAddresses("0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9" as `0x${string}`, "0xd1647800688ccb78c1f378329110fd10791b8af9" as `0x${string}`) },
  USDC: { symbol: "USDC" as const, name: "USD Coin", decimals: 6, addressByChain: makeAddresses("0x5fbdb2315678afecb367f032d93f642f64180aa3" as `0x${string}`, "0xf205032b263672b814d26c81fa6b1c2697855566" as `0x${string}`) },
  DAI:  { symbol: "DAI" as const,  name: "Dai Stablecoin", decimals: 18, addressByChain: makeAddresses("0xe7f1725e7734ce288f8367e1bb143e90bb3f0512" as `0x${string}`, "0xfa30fbba942e92afe1bcfaed35698f360d9f7a97" as `0x${string}`) },
  WBTC: { symbol: "WBTC" as const, name: "Wrapped BTC",  decimals: 8,  addressByChain: makeAddresses("0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0" as `0x${string}`, "0x1ea6c4954ab3632dfccdc676db96a3ec1c6023df" as `0x${string}`) },
};

export const TOKEN_LIST = Object.values(TOKENS);
export const KNOWN_PAIRS = [
  ["WETH", "USDC"],
  ["WETH", "DAI"],
  ["WETH", "WBTC"],
  ["USDC", "DAI"],
  ["USDC", "WBTC"],
  ["DAI", "WBTC"],
] as const;

export function getToken(symbol: "WETH" | "USDC" | "DAI" | "WBTC") { return TOKENS[symbol]; }
export function getTokenAddress(symbol: "WETH" | "USDC" | "DAI" | "WBTC", chainId: number) { return TOKENS[symbol].addressByChain[chainId] ?? null; }
export function isValidAddress(addr: string | null | undefined): addr is `0x${string}` {
  return typeof addr === "string" && addr.length === 42 && addr.startsWith("0x") && addr !== PLACEHOLDER;
}
