// AUTO-GENERATED by scripts/sync-deploy.ts — do not edit by hand.

const PLACEHOLDER = "0x0000000000000000000000000000000000000000" as const;
function makeAddresses(a31337: `0x${string}` | null, a11155111: `0x${string}` | null): Record<number, `0x${string}` | null> {
  return { 31337: a31337, 11155111: a11155111 };
}

// Static metadata; addresses filled in by sync-deploy.
export const TOKENS = {
  WETH: { symbol: "WETH" as const, name: "Wrapped Ether", decimals: 18, addressByChain: makeAddresses("0x610178da211fef7d417bc0e6fed39f05609ad788" as `0x${string}`, null) },
  USDC: { symbol: "USDC" as const, name: "USD Coin", decimals: 6, addressByChain: makeAddresses("0xb7f8bc63bbcad18155201308c8f3540b07f84f5e" as `0x${string}`, null) },
  DAI:  { symbol: "DAI" as const,  name: "Dai Stablecoin", decimals: 18, addressByChain: makeAddresses(null, null) },
  WBTC: { symbol: "WBTC" as const, name: "Wrapped BTC",  decimals: 8,  addressByChain: makeAddresses(null, null) },
};

export const TOKEN_LIST = Object.values(TOKENS);
export const KNOWN_PAIRS = [
  ["WETH", "USDC"],
  ["WETH", "DAI"],
  ["WETH", "WBTC"],
  ["USDC", "DAI"],
  ["USDC", "WBTC"],
  ["DAI", "WBTC"],
] as const;

export function getToken(symbol: "WETH" | "USDC" | "DAI" | "WBTC") { return TOKENS[symbol]; }
export function getTokenAddress(symbol: "WETH" | "USDC" | "DAI" | "WBTC", chainId: number) { return TOKENS[symbol].addressByChain[chainId] ?? null; }
export function isValidAddress(addr: string | null | undefined): addr is `0x${string}` {
  return typeof addr === "string" && addr.length === 42 && addr.startsWith("0x") && addr !== PLACEHOLDER;
}
